version: "3"

services:
  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: S3cr3t
      POSTGRES_DB: wallet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  pgdata:
